# Generated by Django 5.1.7 on 2025-03-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='numbar',
            new_name='number',
        ),
    ]
